### PR TITLE
Working again

### PR DESCRIPTION
**Pull request by AlissonSteffens**
:bug: running (still some problems with eslint)

### CODE REVIEW

**Comment by mateeyow** [comment]
Wondering if we should add some pipeline for testing and linting for this. Was not expecting anyone to pick this up.

**Comment by AlissonSteffens** [comment]
I think eslint is breaking it (https://github.com/facebook/create-react-app/issues/2339#issuecomment-303397558). I had to add ```  /*eslintignore*/ ``` in some files to be able to run it. 

Also, in my opinion, we should focus on the web version.
what do you think?

**Comment by mateeyow** [comment]
Hi @AlissonSteffens, can you specify the changes that you've made? 
Any reason why you deleted some of the files, like Dockerfile and extension files?

**Comment by AlissonSteffens** [comment]
well. I just didn't understand the functions of these files. And, as the project is still running without them, I thought they weren't necessary to be versioned.   Do you think they are important? (Sory if I messed with something, I was just trying to make it run for a project, the original Sizzy is now closed and paid 😞 )

**Comment by mateeyowt** [comment]
I think they are still important. What other problems are you encountering at the moment? Maybe we can create an issue for those and work on them. Meanwhile, I'll close this PR for now.

**Comment by mateeyow** [comment]
I think they are still important. What other problems are you encountering at the moment? Maybe we can create an issue for those and work on them. Meanwhile, I'll close this PR for now.

**Pull request closed without merging**
